language: cpp

compiler:
    - clang
    - gcc

before_install:
    - sudo apt-get update

install:
    - sudo apt-get install scons
    - sudo apt-get install libpoco-dev
    - sudo apt-get install libboost-all-dev

before_script:
    - echo "before script"

script:
    - scons -Q
    - echo "Run Unit Test." && ./unittest
