language: cpp

compiler:
    - clang
    - gcc

before_install:
    - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
    - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi
    - sudo apt-get update -qq

install:
    # g++ 4.8
    - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi
    # clang 3.4
    - if [ "$CXX" == "clang++" ]; then sudo apt-get install --allow-unauthenticated -qq clang-3.4; fi
    - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.4"; fi
    - $CXX --version
    # deps
    - sudo apt-get install libev-dev
    - sudo apt-get install scons
    - sudo apt-get install libpoco-dev
    - sudo apt-get install libboost-all-dev

before_script:
    - echo "before script"

script:
    - scons -Q
    - echo "Run Unit Test." && ./unittest
